manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/artseyio
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: artsey
      import: app/west.yml
  self:
    path: config